### ISSUE TITLE
The method 'canSteal(Player, Player)' has an NPath complexity of 768, current threshold is 200

### ISSUE THREAD

**Issue by Kamesuta** [TeamKun/StealPlugin#5]
#### Occurred on:
+ **Commit**:  719e051b9ddea7d48e0ab098ef305eb5c91efbb0
+ **File**:    [src/main/java/jp/yukiat/stealplugin/Events.java](https://github.com/TeamKun/StealPlugin/blob/719e051b9ddea7d48e0ab098ef305eb5c91efbb0/src/main/java/jp/yukiat/stealplugin/Events.java)
+ **LineNum**: [120](https://github.com/TeamKun/StealPlugin/blob/719e051b9ddea7d48e0ab098ef305eb5c91efbb0/src/main/java/jp/yukiat/stealplugin/Events.java#L120)
+ **Code**:    `private boolean canSteal(Player thief, Player target)`

    
#### Currently on:
+ **Commit**:  2414253b4d16d75e39ef8dc8506411574c2f2aa0
+ **File**:    [src/main/java/jp/yukiat/stealplugin/Events.java](https://github.com/TeamKun/StealPlugin/blob/2414253b4d16d75e39ef8dc8506411574c2f2aa0/src/main/java/jp/yukiat/stealplugin/Events.java)
+ **LineNum**: [133](https://github.com/TeamKun/StealPlugin/blob/2414253b4d16d75e39ef8dc8506411574c2f2aa0/src/main/java/jp/yukiat/stealplugin/Events.java#L133)

**Comment by PeyaPeyaPeyang** [comment]
難解さが41472になり、このIssueは更新されます。
